---
global:
  {{prometheus_global_config and prometheus_global_config|to_nice_yaml(indent=2)|indent(2) or ''}}
  {{prometheus_global_config_raw_raw|indent(2)}}
scrape_configs:
  {{prometheus_scrape_configs and prometheus_scrape_configs|to_nice_yaml(indent=2)|indent(2) or ''}}
  {{prometheus_scrape_configs_raw|indent(2)}}
rule_files: ["/etc/prometheus/rules/*.yml"]
{{prometheus_raw_config}}
